# "simpleSearchReferenceCriteriaId" should be the id of the Simple Search Reference Criteria to be imported
terraform import pingdirectory_simple_search_reference_criteria.mySimpleSearchReferenceCriteria simpleSearchReferenceCriteriaId
