# "passwordPolicyStateJsonVirtualAttributeId" should be the id of the Password Policy State Json Virtual Attribute to be imported
terraform import pingdirectory_password_policy_state_json_virtual_attribute.myPasswordPolicyStateJsonVirtualAttribute passwordPolicyStateJsonVirtualAttributeId
