# "groovyScriptedHttpServletExtensionId" should be the id of the Groovy Scripted Http Servlet Extension to be imported
terraform import pingdirectory_groovy_scripted_http_servlet_extension.myGroovyScriptedHttpServletExtension groovyScriptedHttpServletExtensionId
