# "commonLogFileHttpOperationLogPublisherId" should be the id of the Common Log File Http Operation Log Publisher to be imported
terraform import pingdirectory_common_log_file_http_operation_log_publisher.myCommonLogFileHttpOperationLogPublisher commonLogFileHttpOperationLogPublisherId
