# "thirdPartyConnectionCriteriaId" should be the id of the Third Party Connection Criteria to be imported
terraform import pingdirectory_third_party_connection_criteria.myThirdPartyConnectionCriteria thirdPartyConnectionCriteriaId
