# "hasSubordinatesVirtualAttributeId" should be the id of the Has Subordinates Virtual Attribute to be imported
terraform import pingdirectory_default_has_subordinates_virtual_attribute.myHasSubordinatesVirtualAttribute hasSubordinatesVirtualAttributeId
