# "thirdPartyExtendedOperationHandlerId" should be the id of the Third Party Extended Operation Handler to be imported
terraform import pingdirectory_third_party_extended_operation_handler.myThirdPartyExtendedOperationHandler thirdPartyExtendedOperationHandlerId
