# "syslogJsonHttpOperationLogPublisherId" should be the id of the Syslog Json Http Operation Log Publisher to be imported
terraform import pingdirectory_syslog_json_http_operation_log_publisher.mySyslogJsonHttpOperationLogPublisher syslogJsonHttpOperationLogPublisherId
