# "conjurAuthenticationMethodId" should be the name of the Conjur Authentication Method to be imported
terraform import pingdirectory_conjur_authentication_method.myConjurAuthenticationMethod conjurAuthenticationMethodId
