# "consoleJsonHttpOperationLogPublisherId" should be the id of the Console Json Http Operation Log Publisher to be imported
terraform import pingdirectory_console_json_http_operation_log_publisher.myConsoleJsonHttpOperationLogPublisher consoleJsonHttpOperationLogPublisherId
