# "thirdPartyUncachedEntryCriteriaId" should be the id of the Third Party Uncached Entry Criteria to be imported
terraform import pingdirectory_third_party_uncached_entry_criteria.myThirdPartyUncachedEntryCriteria thirdPartyUncachedEntryCriteriaId
