# "processingTimeHistogramPluginId" should be the id of the Processing Time Histogram Plugin to be imported
terraform import pingdirectory_default_processing_time_histogram_plugin.myProcessingTimeHistogramPlugin processingTimeHistogramPluginId
