# "jvmDefaultTrustManagerProviderId" should be the id of the Jvm Default Trust Manager Provider to be imported
terraform import pingdirectory_jvm_default_trust_manager_provider.myJvmDefaultTrustManagerProvider jvmDefaultTrustManagerProviderId
