# "cleanUpExpiredPingfederatePersistentAccessGrantsPluginId" should be the id of the Clean Up Expired Pingfederate Persistent Access Grants Plugin to be imported
terraform import pingdirectory_clean_up_expired_pingfederate_persistent_access_grants_plugin.myCleanUpExpiredPingfederatePersistentAccessGrantsPlugin cleanUpExpiredPingfederatePersistentAccessGrantsPluginId
