# "fileServerHttpServletExtensionId" should be the id of the File Server Http Servlet Extension to be imported
terraform import pingdirectory_file_server_http_servlet_extension.myFileServerHttpServletExtension fileServerHttpServletExtensionId
