# "thirdPartyAccountStatusNotificationHandlerId" should be the id of the Third Party Account Status Notification Handler to be imported
terraform import pingdirectory_third_party_account_status_notification_handler.myThirdPartyAccountStatusNotificationHandler thirdPartyAccountStatusNotificationHandlerId
