# "subjectEqualsDnCertificateMapperId" should be the id of the Subject Equals Dn Certificate Mapper to be imported
terraform import pingdirectory_subject_equals_dn_certificate_mapper.mySubjectEqualsDnCertificateMapper subjectEqualsDnCertificateMapperId
