# "adminAlertAccountStatusNotificationHandlerId" should be the id of the Admin Alert Account Status Notification Handler to be imported
terraform import pingdirectory_admin_alert_account_status_notification_handler.myAdminAlertAccountStatusNotificationHandler adminAlertAccountStatusNotificationHandlerId
