# "groovyScriptedFileBasedAccessLogPublisherId" should be the id of the Groovy Scripted File Based Access Log Publisher to be imported
terraform import pingdirectory_groovy_scripted_file_based_access_log_publisher.myGroovyScriptedFileBasedAccessLogPublisher groovyScriptedFileBasedAccessLogPublisherId
