# "consentHttpServletExtensionId" should be the id of the Consent Http Servlet Extension to be imported
terraform import pingdirectory_default_consent_http_servlet_extension.myConsentHttpServletExtension consentHttpServletExtensionId
