# "thirdPartySaslMechanismHandlerId" should be the id of the Third Party Sasl Mechanism Handler to be imported
terraform import pingdirectory_third_party_sasl_mechanism_handler.myThirdPartySaslMechanismHandler thirdPartySaslMechanismHandlerId
