# "memberOfServerGroupVirtualAttributeId" should be the id of the Member Of Server Group Virtual Attribute to be imported
terraform import pingdirectory_default_member_of_server_group_virtual_attribute.myMemberOfServerGroupVirtualAttribute memberOfServerGroupVirtualAttributeId
