# "passThroughAuthenticationHandlerId" should be the id of the Pass Through Authentication Handler to be imported
terraform import pingdirectory_pass_through_authentication_handler.myPassThroughAuthenticationHandler passThroughAuthenticationHandlerId
