# "prometheusMonitoringHttpServletExtensionId" should be the id of the Prometheus Monitoring Http Servlet Extension to be imported
terraform import pingdirectory_prometheus_monitoring_http_servlet_extension.myPrometheusMonitoringHttpServletExtension prometheusMonitoringHttpServletExtensionId
