# "groovyScriptedUncachedAttributeCriteriaId" should be the id of the Groovy Scripted Uncached Attribute Criteria to be imported
terraform import pingdirectory_groovy_scripted_uncached_attribute_criteria.myGroovyScriptedUncachedAttributeCriteria groovyScriptedUncachedAttributeCriteriaId
