# "thirdPartyFileBasedErrorLogPublisherId" should be the id of the Third Party File Based Error Log Publisher to be imported
terraform import pingdirectory_third_party_file_based_error_log_publisher.myThirdPartyFileBasedErrorLogPublisher thirdPartyFileBasedErrorLogPublisherId
