# "thirdPartyFileBasedAccessLogPublisherId" should be the id of the Third Party File Based Access Log Publisher to be imported
terraform import pingdirectory_third_party_file_based_access_log_publisher.myThirdPartyFileBasedAccessLogPublisher thirdPartyFileBasedAccessLogPublisherId
