# "privilegeDataSecurityAuditorId" should be the id of the Privilege Data Security Auditor to be imported
terraform import pingdirectory_privilege_data_security_auditor.myPrivilegeDataSecurityAuditor privilegeDataSecurityAuditorId
