# "unboundidCertificatePlusPasswordSaslMechanismHandlerId" should be the id of the Unboundid Certificate Plus Password Sasl Mechanism Handler to be imported
terraform import pingdirectory_default_unboundid_certificate_plus_password_sasl_mechanism_handler.myUnboundidCertificatePlusPasswordSaslMechanismHandler unboundidCertificatePlusPasswordSaslMechanismHandlerId
