version: '3.7'
services:
  pingdirectory:
    image: "pingidentity/pingdirectory:10.0.0.0-latest"
    ports:
      - "1389:1389"
      - "1636:1636"
      - "1443:1443"
    environment:
      # Tone down the amount of output from the container
      - TAIL_LOG_FILES=
    env_file:
      - ${HOME}/.pingidentity/config
