# "genericWebApplicationExtensionId" should be the id of the Generic Web Application Extension to be imported
terraform import pingdirectory_generic_web_application_extension.myGenericWebApplicationExtension genericWebApplicationExtensionId
