# "pingFederateAccessTokenValidatorId" should be the id of the Ping Federate Access Token Validator to be imported
terraform import pingdirectory_ping_federate_access_token_validator.myPingFederateAccessTokenValidator pingFederateAccessTokenValidatorId
