# "getSupportedOtpDeliveryMechanismsExtendedOperationHandlerId" should be the id of the Get Supported Otp Delivery Mechanisms Extended Operation Handler to be imported
terraform import pingdirectory_default_get_supported_otp_delivery_mechanisms_extended_operation_handler.myGetSupportedOtpDeliveryMechanismsExtendedOperationHandler getSupportedOtpDeliveryMechanismsExtendedOperationHandlerId
