# "getChangelogBatchExtendedOperationHandlerId" should be the id of the Get Changelog Batch Extended Operation Handler to be imported
terraform import pingdirectory_default_get_changelog_batch_extended_operation_handler.myGetChangelogBatchExtendedOperationHandler getChangelogBatchExtendedOperationHandlerId
