# "ldapPassThroughScimResourceTypeId" should be the id of the Ldap Pass Through Scim Resource Type to be imported
terraform import pingdirectory_ldap_pass_through_scim_resource_type.myLdapPassThroughScimResourceType ldapPassThroughScimResourceTypeId
