# "delegatedAdminHttpServletExtensionId" should be the id of the Delegated Admin Http Servlet Extension to be imported
terraform import pingdirectory_default_delegated_admin_http_servlet_extension.myDelegatedAdminHttpServletExtension delegatedAdminHttpServletExtensionId
