# "disabledAccountDataSecurityAuditorId" should be the id of the Disabled Account Data Security Auditor to be imported
terraform import pingdirectory_disabled_account_data_security_auditor.myDisabledAccountDataSecurityAuditor disabledAccountDataSecurityAuditorId
