# "accountStatusNotificationHandlerId" should be the name of the Account Status Notification Handler to be imported
terraform import pingdirectory_account_status_notification_handler.myAccountStatusNotificationHandler accountStatusNotificationHandlerId
