# "weaklyEncodedPasswordDataSecurityAuditorId" should be the id of the Weakly Encoded Password Data Security Auditor to be imported
terraform import pingdirectory_weakly_encoded_password_data_security_auditor.myWeaklyEncodedPasswordDataSecurityAuditor weaklyEncodedPasswordDataSecurityAuditorId
