# "thirdPartyHttpServletExtensionId" should be the id of the Third Party Http Servlet Extension to be imported
terraform import pingdirectory_third_party_http_servlet_extension.myThirdPartyHttpServletExtension thirdPartyHttpServletExtensionId
