# "auditDataSecurityRecurringTaskId" should be the id of the Audit Data Security Recurring Task to be imported
terraform import pingdirectory_audit_data_security_recurring_task.myAuditDataSecurityRecurringTask auditDataSecurityRecurringTaskId
