# "generateServerProfileRecurringTaskName" should be the name of the Generate Server Profile Recurring Task to be imported
terraform import pingdirectory_generate_server_profile_recurring_task generateServerProfileRecurringTaskName
