# "availabilityStateHttpServletExtensionId" should be the id of the Availability State Http Servlet Extension to be imported
terraform import pingdirectory_availability_state_http_servlet_extension.myAvailabilityStateHttpServletExtension availabilityStateHttpServletExtensionId
