# "passwordPolicyStateExtendedOperationHandlerId" should be the id of the Password Policy State Extended Operation Handler to be imported
terraform import pingdirectory_default_password_policy_state_extended_operation_handler.myPasswordPolicyStateExtendedOperationHandler passwordPolicyStateExtendedOperationHandlerId
