# "replicationSynchronizationProviderId" should be the id of the Replication Synchronization Provider to be imported
terraform import pingdirectory_default_replication_synchronization_provider.myReplicationSynchronizationProvider replicationSynchronizationProviderId
