# "quickstartHttpServletExtensionId" should be the id of the Quickstart Http Servlet Extension to be imported
terraform import pingdirectory_quickstart_http_servlet_extension.myQuickstartHttpServletExtension quickstartHttpServletExtensionId
