# "passwordModifyExtendedOperationHandlerId" should be the id of the Password Modify Extended Operation Handler to be imported
terraform import pingdirectory_default_password_modify_extended_operation_handler.myPasswordModifyExtendedOperationHandler passwordModifyExtendedOperationHandlerId
