# "attributeBasedLogFieldSyntaxId" should be the id of the Attribute Based Log Field Syntax to be imported
terraform import pingdirectory_default_attribute_based_log_field_syntax.myAttributeBasedLogFieldSyntax attributeBasedLogFieldSyntaxId
