# "aggregateSearchEntryCriteriaId" should be the id of the Aggregate Search Entry Criteria to be imported
terraform import pingdirectory_aggregate_search_entry_criteria.myAggregateSearchEntryCriteria aggregateSearchEntryCriteriaId
