# "velocityHttpServletExtensionId" should be the id of the Velocity Http Servlet Extension to be imported
terraform import pingdirectory_default_velocity_http_servlet_extension.myVelocityHttpServletExtension velocityHttpServletExtensionId
