# "cleanUpExpiredPingfederatePersistentSessionsPluginId" should be the id of the Clean Up Expired Pingfederate Persistent Sessions Plugin to be imported
terraform import pingdirectory_clean_up_expired_pingfederate_persistent_sessions_plugin.myCleanUpExpiredPingfederatePersistentSessionsPlugin cleanUpExpiredPingfederatePersistentSessionsPluginId
