# "groovyScriptedHttpOperationLogPublisherId" should be the id of the Groovy Scripted Http Operation Log Publisher to be imported
terraform import pingdirectory_groovy_scripted_http_operation_log_publisher.myGroovyScriptedHttpOperationLogPublisher groovyScriptedHttpOperationLogPublisherId
