# "freeDiskSpaceLogRetentionPolicyId" should be the id of the Free Disk Space Log Retention Policy to be imported
terraform import pingdirectory_free_disk_space_log_retention_policy.myFreeDiskSpaceLogRetentionPolicy freeDiskSpaceLogRetentionPolicyId
