# "smtpAccountStatusNotificationHandlerId" should be the id of the Smtp Account Status Notification Handler to be imported
terraform import pingdirectory_smtp_account_status_notification_handler smtpAccountStatusNotificationHandlerId
