# "unboundidTotpSaslMechanismHandlerId" should be the id of the Unboundid Totp Sasl Mechanism Handler to be imported
terraform import pingdirectory_default_unboundid_totp_sasl_mechanism_handler.myUnboundidTotpSaslMechanismHandler unboundidTotpSaslMechanismHandlerId
