# "usernamePasswordAzureAuthenticationMethodId" should be the id of the Username Password Azure Authentication Method to be imported
terraform import pingdirectory_username_password_azure_authentication_method.myUsernamePasswordAzureAuthenticationMethod usernamePasswordAzureAuthenticationMethodId
