# "replicationAssurancePolicyId" should be the name of the Replication Assurance Policy to be imported
terraform import pingdirectory_replication_assurance_policy.myReplicationAssurancePolicy replicationAssurancePolicyId
