# "replicationAssurancePolicyId" should be the id of the Replication Assurance Policy to be imported
terraform import pingdirectory_replication_assurance_policy.myReplicationAssurancePolicy replicationAssurancePolicyId
