# "instanceNameVirtualAttributeId" should be the id of the Instance Name Virtual Attribute to be imported
terraform import pingdirectory_default_instance_name_virtual_attribute.myInstanceNameVirtualAttribute instanceNameVirtualAttributeId
