# "unboundidExternalAuthSaslMechanismHandlerId" should be the id of the Unboundid External Auth Sasl Mechanism Handler to be imported
terraform import pingdirectory_default_unboundid_external_auth_sasl_mechanism_handler.myUnboundidExternalAuthSaslMechanismHandler unboundidExternalAuthSaslMechanismHandlerId
