# "generalizedTimeAttributeSyntaxId" should be the id of the Generalized Time Attribute Syntax to be imported
terraform import pingdirectory_default_generalized_time_attribute_syntax.myGeneralizedTimeAttributeSyntax generalizedTimeAttributeSyntaxId
