# "groovyScriptedFileBasedErrorLogPublisherId" should be the id of the Groovy Scripted File Based Error Log Publisher to be imported
terraform import pingdirectory_groovy_scripted_file_based_error_log_publisher.myGroovyScriptedFileBasedErrorLogPublisher groovyScriptedFileBasedErrorLogPublisherId
