# "staticallyDefinedRecurringTaskId" should be the id of the Statically Defined Recurring Task to be imported
terraform import pingdirectory_statically_defined_recurring_task.myStaticallyDefinedRecurringTask staticallyDefinedRecurringTaskId
