# "cancelExtendedOperationHandlerId" should be the id of the Cancel Extended Operation Handler to be imported
terraform import pingdirectory_default_cancel_extended_operation_handler.myCancelExtendedOperationHandler cancelExtendedOperationHandlerId
