# "pluggablePassThroughAuthenticationPluginId" should be the id of the Pluggable Pass Through Authentication Plugin to be imported
terraform import pingdirectory_pluggable_pass_through_authentication_plugin.myPluggablePassThroughAuthenticationPlugin pluggablePassThroughAuthenticationPluginId
