# "thirdPartyUncachedAttributeCriteriaId" should be the id of the Third Party Uncached Attribute Criteria to be imported
terraform import pingdirectory_third_party_uncached_attribute_criteria.myThirdPartyUncachedAttributeCriteria thirdPartyUncachedAttributeCriteriaId
