# "changeSubscriptionNotificationPluginId" should be the id of the Change Subscription Notification Plugin to be imported
terraform import pingdirectory_default_change_subscription_notification_plugin.myChangeSubscriptionNotificationPlugin changeSubscriptionNotificationPluginId
