# "thirdPartySearchReferenceCriteriaId" should be the id of the Third Party Search Reference Criteria to be imported
terraform import pingdirectory_third_party_search_reference_criteria.myThirdPartySearchReferenceCriteria thirdPartySearchReferenceCriteriaId
