name: Go Package Dependencies
on:
  pull_request:
    paths:
        - 'go.mod'
        - 'go.sum'

jobs:
  check-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "PR created by Dependabot"
  check-dev:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - run: echo "PR created by developer"