name: Issues Workflow

on:
  issues:
    types: [opened]

env:
  WORKFLOW_URL: ${{ secrets.WORKFLOW_URL }}
  ACTION: "${{ github.event.action }}"
  DESCRIPTION: "${{ github.event.issue.body }}"
  NUMBER : "${{ github.event.issue.number }}"
  TITLE : "${{ github.event.issue.title }}"
  URL : "${{ github.event.issue.html_url }}"
     
jobs:       
  issue_created:
    name: Issue Created
    if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl --silent --location --request POST "$WORKFLOW_URL" \
          --header 'Accept: application/json' \
          --header 'Content-Type: text/plain' \
          --data-raw '{
              "action": "'"$ACTION"'",
              "description": "'"$DESCRIPTION"'",
              "number" : "'"$NUMBER"'",
              "title" : "'"$TITLE"'",
              "url" : "'"$URL"'"
          }'