name: Pull Request
on:
  pull_request:
    paths:
      - '.github/workflows/code-check-and-tests.yaml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pull request created..."